# The `site.yml` blueprint defines the look of the start page (Dashboard) of the Panel.
# More about the site blueprint: https://getkirby.com/docs/reference/panel/blueprints/site

columns:
  - width: 1
    sections:
      pages:
        type: pages
        layout: list
